version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      # - echo Installing source NPM dependencies...
      # - npm install unit.js
      - cp -R $CODEBUILD_SRC_DIR_BuildArtifact02 .
      - ls
  post_build:
    commands:
      - echo Build completed `date`
artifacts:
  files:
    - '**/*'
